services:
  app:
    image: order-service:latest
    container_name: order-service
    restart: always
    environment:
      SPRING_PROFILES_ACTIVE: local
      SPRING_DATASOURCE_URL: jdbc:mariadb://db:3306/commerce-order
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin1234
      SPRING_KAFKA_BOOTSTRAP_SERVERS: host.docker.internal:9092
    ports:
      - "8085:8085"
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8084/actuator/health/liveness"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 60s
    networks:
      - commerce-net

networks:
  commerce-net:
    external: true
